### ISSUE TITLE
Understanding Effects of Actions

### ISSUE THREAD

**Issue by AdamIshay** [izuminka/reasoning_about_actions#25]
Dear Authors,

I am trying to understand a specific kind of question from the category "effects of actions". Specifically, the type which read like: "In this state, if \<ACTIONS\> happen, is it True or False that no properties of the state change?"

I take properties to mean fluents, so in the following example (id: 5da02299-8958-43c0-b751-5cfba25b0907), I would expect the label to be "False", since stacking block b3 on b5 means that on(b3,b5) is changing from false to true but it is "True".

> Block b1 is on the table, block b2 is clear, block b2 is on block b4, block b3 is on top of block b8, block b4 is on the table, block b5 is on the table, block b6 is clear, block b6 is on block b3, block b7 is clear, block b7 is on top of block b1, block b8 is on top of block b5 and hand is empty.
> 
> Given the initial condition, the following actions are performed: from top of block b4, block b2 is unstacked, on top of block b6, block b2 is stacked, block b7 is unstacked from top of block b1, on top of block b4, block b7 is stacked, block b2 is unstacked from top of block b6, on top of block b7, block b2 is stacked, block b1 is picked up by the hand, block b1 is stacked on top of block b2, from top of block b3, block b6 is unstacked, the hand puts down the block b6, block b3 is unstacked from top of block b8, block b3 is put down on the table, from top of block b5, block b8 is unstacked, on top of block b1, block b8 is stacked, block b6 is picked up, on top of block b8, block b6 is stacked, block b5 is picked up by the hand, block b5 is stacked on top of block b6 and block b3 is picked up to reach the current state. In this state, if on top of block b5, block b3 is stacked, is it True or False that no properties of the state change?

In another example, the label is the opposite ("False"), which I cannot figure out (id: a5f1833e-feae-4c45-bcdd-99c287f227c8):

> Block b1 is on the table, block b2 is clear, block b2 is on block b4, block b3 is on top of block b8, block b4 is on the table, block b5 is on the table, block b6 is clear, block b6 is on block b3, block b7 is clear, block b7 is on top of block b1, block b8 is on top of block b5 and hand is empty.
> 
> Given the initial condition, the following actions are performed: block b2 is unstacked from top of block b4, block b2 is stacked on top of block b6, block b7 is unstacked from block b1, on top of block b4, block b7 is stacked, from top of block b6, block b2 is unstacked, on top of block b7, block b2 is stacked, block b1 is picked up from the table, block b1 is stacked on top of block b2, block b6 is unstacked from top of block b3, the hand puts down the block b6, from top of block b8, block b3 is unstacked, block b3 is put down on the table, block b8 is unstacked from top of block b5, block b8 is stacked on top of block b1, block b6 is picked up from the table, block b6 is stacked on top of block b8, block b5 is picked up, on top of block b6, block b5 is stacked and block b3 is picked up to reach the current state. In this state, if block b3 is stacked on top of block b5, is it True or False that no properties of the state change?

Thank you for any help.

**Comment by izuminka** [comment]
Thank you for pointing out the issues. We have regenerated the dataset and rerun the experiments.
The results and new data is available at https://drive.google.com/drive/folders/1v8yhRmd2IhLLNpiJhoh4fyiaKEcaI9_B?usp=sharing
